# -*- coding: utf-8 -*-
"""
    pygments.lexers.c_cpp
    ~~~~~~~~~~~~~~~~~~~~~

    Lexers for C/C++ w/ OSPRay API calls

    :copyright: Copyright 2006-2019 by the Pygments team, see AUTHORS.
    :license: BSD, see LICENSE for details.
"""

import re

from pygments.lexer import RegexLexer, include, bygroups, using, \
    this, inherit, default, words
from pygments.util import get_bool_opt
from pygments.token import Text, Comment, Operator, Keyword, Name, String, \
    Number, Punctuation, Error

from pygments.lexers.c_cpp import CLexer, CppLexer

__all__ = ['OSPRayCLexer']

class OSPRayCLexer(CLexer):
    name = "OSPRayCLexer"
    filename = ["*.h", "*.c"]
    aliases = ["c"]
    mimetypes = ["text/x-c"]

    ospray_types = set((
        "OSPStatusFunc",
        "OSPErrorFunc",
        "OSPBounds",
        "OSPPickResult",
        "OSPDevice",
        "OSPCamera",
        "OSPData",
        "OSPFrameBuffer",
        "OSPFuture",
        "OSPGeometricModel",
        "OSPGeometry",
        "OSPGroup",
        "OSPImageOperation",
        "OSPInstance",
        "OSPLight",
        "OSPObject",
        "OSPMaterial",
        "OSPRenderer",
        "OSPTexture",
        "OSPTransferFunction",
        "OSPVolume",
        "OSPVolumetricModel",
        "OSPWorld",
        "OSPLogLevel",
        "OSPDeviceProperty",
        "OSPDataType",
        "OSPTextureFormat",
        "OSPTextureFilter",
        "OSPError",
        "OSPFrameBufferFormat",
        "OSPFrameBufferChannel",
        "OSPSyncEvent",
        "OSPUnstructuredCellType",
        "OSPStereoMode",
        "OSPCurveType",
        "OSPCurveBasis",
        "OSPAMRMethod",
        "OSPSubdivisionMode"
    ))

    ospray_functions = set((
        "ospInit",
        "ospDeviceGetProperty",
        "ospShutdown",
        "ospNewDevice",
        "ospSetCurrentDevice",
        "ospGetCurrentDevice",
        "ospDeviceSetParam",
        "ospDeviceRemoveParam",
        "ospDeviceSetStatusFunc",
        "ospDeviceSetErrorFunc",
        "ospDeviceGetLastErrorCode",
        "ospDeviceGetLastErrorMsg",
        "ospDeviceCommit",
        "ospDeviceRelease",
        "ospDeviceRetain",
        "ospLoadModule",
        "ospNewSharedData",
        "ospNewData",
        "ospCopyData",
        "ospNewLight",
        "ospNewCamera",
        "ospNewGeometry",
        "ospNewVolume",
        "ospNewGeometricModel",
        "ospNewVolumetricModel",
        "ospNewMaterial",
        "ospNewTransferFunction",
        "ospNewTexture",
        "ospNewGroup",
        "ospNewInstance",
        "ospNewWorld",
        "ospGetBounds",
        "ospSetParam",
        "ospRemoveParam",
        "ospCommit",
        "ospRelease",
        "ospRetain",
        "ospNewFrameBuffer",
        "ospNewImageOperation",
        "ospMapFrameBuffer",
        "ospUnmapFrameBuffer",
        "ospGetVariance",
        "ospResetAccumulation",
        "ospNewRenderer",
        "ospRenderFrame",
        "ospIsReady",
        "ospWait",
        "ospCancel",
        "ospGetProgress",
        "ospPick",
        "ospNewSharedData1D",
        "ospNewSharedData1DStride",
        "ospNewSharedData2D",
        "ospNewSharedData2DStride",
        "ospNewSharedData3D",
        "ospNewData1D",
        "ospNewData2D",
        "ospCopyData1D",
        "ospCopyData2D",
        "ospSetString",
        "ospSetObject",
        "ospSetBool",
        "ospSetFloat",
        "ospSetInt",
        "ospSetVec2f",
        "ospSetVec3f",
        "ospSetVec4f",
        "ospSetVec2i",
        "ospSetVec3i",
        "ospSetVec4i",
        "ospSetObjectAsData",
        "ospRenderFrameBlocking"
    ))

    ospray_constants = set((
        "OSP_LOG_DEBUG",
        "OSP_LOG_INFO",
        "OSP_LOG_WARNING",
        "OSP_LOG_ERROR",
        "OSP_LOG_NONE",
        "OSP_DEVICE_VERSION",
        "OSP_DEVICE_VERSION_MAJOR",
        "OSP_DEVICE_VERSION_MINOR",
        "OSP_DEVICE_VERSION_PATCH",
        "OSP_DEVICE_SO_VERSION",
        "OSP_DEVICE",
        "OSP_VOID_PTR",
        "OSP_BOOL",
        "OSP_OBJECT",
        "OSP_DATA",
        "OSP_CAMERA",
        "OSP_FRAMEBUFFER",
        "OSP_FUTURE",
        "OSP_GEOMETRIC_MODEL",
        "OSP_GEOMETRY",
        "OSP_GROUP",
        "OSP_IMAGE_OPERATION",
        "OSP_INSTANCE",
        "OSP_LIGHT",
        "OSP_MATERIAL",
        "OSP_RENDERER",
        "OSP_TEXTURE",
        "OSP_TRANSFER_FUNCTION",
        "OSP_VOLUME",
        "OSP_VOLUMETRIC_MODEL",
        "OSP_WORLD",
        "OSP_STRING",
        "OSP_CHAR",
        "OSP_UCHAR",
        "OSP_VEC2UC",
        "OSP_VEC3UC",
        "OSP_VEC4UC",
        "OSP_BYTE",
        "OSP_RAW",
        "OSP_SHORT",
        "OSP_USHORT",
        "OSP_INT",
        "OSP_VEC2I",
        "OSP_VEC3I",
        "OSP_VEC4I",
        "OSP_UINT",
        "OSP_VEC2UI",
        "OSP_VEC3UI",
        "OSP_VEC4UI",
        "OSP_LONG",
        "OSP_VEC2L",
        "OSP_VEC3L",
        "OSP_VEC4L",
        "OSP_ULONG",
        "OSP_VEC2UL",
        "OSP_VEC3UL",
        "OSP_VEC4UL",
        "OSP_FLOAT",
        "OSP_VEC2F",
        "OSP_VEC3F",
        "OSP_VEC4F",
        "OSP_DOUBLE",
        "OSP_BOX1I",
        "OSP_BOX2I",
        "OSP_BOX3I",
        "OSP_BOX4I",
        "OSP_BOX1F",
        "OSP_BOX2F",
        "OSP_BOX3F",
        "OSP_BOX4F",
        "OSP_LINEAR2F",
        "OSP_LINEAR3F",
        "OSP_AFFINE2F",
        "OSP_AFFINE3F",
        "OSP_UNKNOWN",
        "OSP_TEXTURE_RGBA8",
        "OSP_TEXTURE_SRGBA",
        "OSP_TEXTURE_RGBA32F",
        "OSP_TEXTURE_RGB8",
        "OSP_TEXTURE_SRGB",
        "OSP_TEXTURE_RGB32F",
        "OSP_TEXTURE_R8",
        "OSP_TEXTURE_R32F",
        "OSP_TEXTURE_L8",
        "OSP_TEXTURE_RA8",
        "OSP_TEXTURE_LA8",
        "OSP_TEXTURE_FORMAT_INVALID",
        "OSP_TEXTURE_FILTER_BILINEAR",
        "OSP_TEXTURE_FILTER_NEAREST",
        "OSP_NO_ERROR",
        "OSP_UNKNOWN_ERROR",
        "OSP_INVALID_ARGUMENT",
        "OSP_INVALID_OPERATION",
        "OSP_OUT_OF_MEMORY",
        "OSP_UNSUPPORTED_CPU",
        "OSP_VERSION_MISMATCH",
        "OSP_FB_NONE",
        "OSP_FB_RGBA8",
        "OSP_FB_SRGBA",
        "OSP_FB_RGBA32F",
        "OSP_FB_COLOR",
        "OSP_FB_DEPTH",
        "OSP_FB_ACCUM",
        "OSP_FB_VARIANCE",
        "OSP_FB_NORMAL",
        "OSP_FB_ALBEDO",
        "OSP_NONE_FINISHED",
        "OSP_WORLD_RENDERED",
        "OSP_WORLD_COMMITTED",
        "OSP_FRAME_FINISHED",
        "OSP_TASK_FINISHED",
        "OSP_TETRAHEDRON",
        "OSP_HEXAHEDRON",
        "OSP_WEDGE",
        "OSP_PYRAMID",
        "OSP_UNKNOWN_CELL_TYPE",
        "OSP_STEREO_NONE",
        "OSP_STEREO_LEFT",
        "OSP_STEREO_RIGHT",
        "OSP_STEREO_SIDE_BY_SIDE",
        "OSP_STEREO_UNKNOWN",
        "OSP_ROUND",
        "OSP_FLAT",
        "OSP_RIBBON",
        "OSP_UNKNOWN_CURVE_TYPE",
        "OSP_LINEAR",
        "OSP_BEZIER",
        "OSP_BSPLINE",
        "OSP_HERMITE",
        "OSP_CATMULL_ROM",
        "OSP_UNKNOWN_CURVE_BASIS",
        "OSP_AMR_CURRENT",
        "OSP_AMR_FINEST",
        "OSP_AMR_OCTANT",
        "OSP_SUBDIVISION_NO_BOUNDARY",
        "OSP_SUBDIVISION_SMOOTH_BOUNDARY",
        "OSP_SUBDIVISION_PIN_CORNERS",
        "OSP_SUBDIVISION_PIN_BOUNDARY",
        "OSP_SUBDIVISION_PIN_ALL"
    ))
    
    def get_tokens_unprocessed(self, text):
        for index, token, value in CLexer.get_tokens_unprocessed(self, text):
            if token is Name:
                if value in self.ospray_types:
                    token = Keyword.Type
                elif value in self.ospray_functions:
                    token = Keyword.Function
                elif value in self.ospray_constants:
                    token = Keyword.Constant
            yield index, token, value

